<?php
/**
 *  Module creates my custom page with a single message,
 *  uses JS, creates 404 and 403 error message
 *  pages and creates a block.
 */

/**
 *  Implements hook_menu with three pages.
 */
function shedow_module_menu() {
$items = array();
$items['shedow_page'] = array(
  'title' => t('Simple page'),
  'description' => t('Simple custom page'),
  'page callback' => 'shedow_page_content',
  'file' => 'shedow.pages.inc',
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM,
  'menu_name' => 'main-menu',
);
$items['page-not-found'] = array(
  'title' => t('Not Found'),
  'page callback' => 'not_found_content',
  'access callback' => TRUE,
  'type' => MENU_CALLBACK,
  'file' => 'shedow.pages.inc',
);
$items['access-denied'] = array(
  'title' => t('Access denied'),
  'page callback' => 'access_denied_content',
  'access callback' => TRUE,
  'type' => MENU_CALLBACK,
  'file' => 'shedow.pages.inc',
);
  return $items;
}

/**
 *  block_info function for my custom block.
 */
function shedow_module_block_info() {
  $blocks = array();
  $blocks['shedow_block'] = array(
    'info' => t('Shedow Block')
  );
  return $blocks;
}

/**
 *  Function for viewing my block.
 */
function shedow_module_block_view($delta = '') {
  $block = array();
  if ($delta == 'shedow_block') {
    $block['subject'] = t('New cinema is open');
    if(user_access('view_shedow_module'))
      $block['content'] = t('New cinema is open in Port City. You can watch newest films in 3d here. Come and visit this place.');
    else
      $block['content'] = t('Access to view this content is denied');
  }
  return $block;
}

/**
 *  Implements hook_permission for my hook.
 */
function shedow_module_permission() {
  return array(
    'view_shedow_module' => array(
      'title' => t('View Shedow Module'),
      'description' => t('Permission to view shedow module content'),
      ),
  );
}

/**
 * Implements hook_shedow_my_module_alter() for drupal_alter.
 */
function shedow_module_shedow_my_module_alter($data) {
  drupal_set_message($data);
  drupal_add_js('jQuery(document).ready(function () {alert("Hello!"); });', 'inline');
}
